name: 功能请求
description: 请求新的功能
title: "[功能]："

body:
  - type: textarea
    attributes:
      label: 功能描述
    validations:
      required: true
     
  - type: textarea
    attributes:
      label: 解决的问题
      
  - type: textarea
    attributes:
      label: 附加信息

  - type: dropdown
    attributes:
      label: 愿意提交 PR 吗？
      description: 为此功能提交 PR。（并非强制要求，但我们感谢您的贡献！）
      options:
        - 愿意
        - 不愿意